# required
version: 1.0.0

# required
app_help_description:
  # required fields:
  app_name: "example1"
  name_help_info: "shows how argtools generator works"
  description_help_info:
    - "you can write more detailed description here"

# required
help_command_description:
  command: "help"
  # optional fields
  additional_commands:
    - "-h"

# optional
flag_descriptions:
  - flag: &checkCommandArguments "-check"
    description_help_info: "check command arguments types"
    # optional fields
    arguments_description:
      # required fields
      amount_type: "single"
      synopsis_description: "str"
      # optional fields:
      arguments_description:
        amount_type: "single"
        synopsis_description: "log level"
        default_values:
          - "s"
        allowed_values:
          - "s"
          - "i"
          - "f"

  - flag: &flagStringSingle "-s"
    description_help_info: "single string"
    # optional fields
    arguments_description:
      # required fields
      amount_type: "single"
      synopsis_description: "str"

  - flag: &flagStringList "-sl"
    description_help_info: "string list"
    # optional fields
    arguments_description:
      # required fields
      amount_type: "list"
      synopsis_description: "str"

  - flag: &flagIntSingle "-i"
    description_help_info: "int string"
    # optional fields
    arguments_description:
      # required fields
      amount_type: "single"
      synopsis_description: "str"

  - flag: &flagIntList "-il"
    description_help_info: "int list"
    # optional fields
    arguments_description:
      # required fields
      amount_type: "list"
      synopsis_description: "str"

  - flag: &flagFloatSingle "-f"
    description_help_info: "single float"
    # optional fields
    arguments_description:
      # required fields
      amount_type: "single"
      synopsis_description: "str"

  - flag: &flagFloatList "-fl"
    description_help_info: "float list"
    # optional fields
    arguments_description:
      # required fields
      amount_type: "list"
      synopsis_description: "str"

  - flag: &doTypeCheckingFlag "-checkargs"
    description_help_info: "do arguments checking"

# optional
nameless_command_description:
  # required
  description_help_info: "checks arguments types"
  # optional fields
  arguments_description:
    # required fields
    amount_type: "list"
    synopsis_description: "str list"
  required_flags:
    - *checkCommandArguments

# optional
command_descriptions:
  - command: "print"
    description_help_info: "print command line arguments with optional checking"
    # optional fields
    arguments_description:
      amount_type: "list"
      synopsis_description: "value"
    optional_flags:
      - *flagStringSingle
      - *flagStringList
      - *flagIntSingle
      - *flagIntList
      - *flagFloatSingle
      - *flagFloatList
      - *doTypeCheckingFlag
