// This code was generated by argtools.generator. DO NOT EDIT

package argTools

import (
	"github.com/terryhay/argtools/internal/argParserImpl"
	"github.com/terryhay/argtools/pkg/argParserConfig"
	"github.com/terryhay/argtools/pkg/argtoolsError"
	"github.com/terryhay/argtools/pkg/helpPrinter"
	"github.com/terryhay/argtools/pkg/parsedData"
)

const (
	// CommandIDNamelessCommand - runs example3
	CommandIDNamelessCommand argParserConfig.CommandID = iota + 1
	// CommandIDHelp - print help info
	CommandIDHelp
)

const (
	// CommandH - print help info
	CommandH argParserConfig.Command = "-h"
	// CommandHelp - print help info
	CommandHelp = "help"
)

const ()

// Parse - processes command line arguments
func Parse(args []string) (res *parsedData.ParsedData, err *argtoolsError.Error) {
	appArgConfig := argParserConfig.NewArgParserConfig(
		// appDescription
		argParserConfig.ApplicationDescription{
			AppName:      "example3",
			NameHelpInfo: "shows how argtools generator works without commands and flags",
			DescriptionHelpInfo: []string{
				"you can write more detailed description here",
			},
		},
		// flagDescriptions
		nil,
		// commandDescriptions
		[]*argParserConfig.CommandDescription{
			{
				ID: CommandIDHelp,
				Commands: map[argParserConfig.Command]bool{
					CommandHelp: true,
					CommandH:    true,
				},
			},
		},
		// namelessCommandDescription
		&argParserConfig.NamelessCommandDescription{
			ID:                  CommandIDNamelessCommand,
			DescriptionHelpInfo: "runs example3"},
	)

	if res, err = argParserImpl.NewCmdArgParserImpl(appArgConfig).Parse(args); err != nil {
		return nil, err
	}

	if res.GetCommandID() == CommandIDHelp {
		helpPrinter.PrintHelpInfo(appArgConfig)
		return nil, nil
	}

	return res, nil
}
